### ISSUE TITLE
Funds missing 

### ISSUE THREAD

**Issue by Uplander007** [AcalaNetwork/polkawallet_plugin_karura#2]
Hello Karura Team,
I am having issues with my Polkawallet. For Past 2 days my staked kusd/ksm/kar have vanished from my wallet. In ksm/kusd liquidity pool I was having roundly 800+ kusd & 1.9+ KSM. I don’t see any outbound transfer. So I believe it’s a bug.

It will be great if you can fix the issue

**Comment by RomeroYang** [comment]
You need to upgrade to v2.3.4 to see your funds data due to blockchain runtime update. The Android versions were released but the ios version is still waiting for review of AppStore. You may see a v2.3.4 update in AppStore tomorrow.

**Comment by Uplander007** [comment]
Thanks for the update. Cheers
