### ISSUE TITLE
Token not recived 

### ISSUE THREAD

**Issue by Vishwa0405** [AcalaNetwork/polkawallet_plugin_karura#9]
I have transferred some BNC from karura_polkawallet to gate.io transfere stuck because they did not support karura_BNC. And only support mainnet_BNC 

How the 2 BNC are different.

Now they are not able to transfer that BNC in my gate.io wallet because it is karura_BNC what should I do. It has been already 1 month.

Please suggest me solution and what should I do to get back that tokens.

![20211023_203902](https://user-images.githubusercontent.com/93084347/142727408-155e1ecc-9c33-4a02-ae28-c08628251040.jpg)

**Comment by Vishwa0405** [comment]
https://github.com/AcalaNetwork/polkawallet_plugin_karura/issues/5#issuecomment-951644764

**Comment by RomeroYang** [comment]
As I said in #5 ,

**Comment by Vishwa0405** [comment]
Than why I am not able to see the BNC In gate account.

**Comment by Vishwa0405** [comment]
Please provide solution so that I can transfer it in any of usable accounts

**Comment by RomeroYang** [comment]
1. Where are the tokens ? -- on address `eqsYaNjVfVSuikQZz7xB17cstXgqtnMqm7p3uW5MokAUB2G `.
2. Who has the address eqsYaNjVfVSuikQZz7xB17cstXgqtnMqm7p3uW5MokAUB2G ? -- gate.io.
